[API]
Port = 9085                                     # The port number that the web server listens on
MultiAddress = "/ip4/<PUBLIC_IP>/tcp/<PORT>"    # The multiAddress for libp2p
Domain = "<YOUR_CP_Domain>"                     # The domain name
NodeName = "<YOUR_CP_Node_Name>"                 # The computing-provider node name

RedisUrl = "redis://127.0.0.1:16379"             # The redis server address
RedisPassword = "rootadmin!213"                  # The redis server access password, default password
WalletWhiteList = ""                             #

[UBI]
UbiTask = false                                               # Accept the UBI task (Default: true)
UbiEnginePk = "0xB5aeb540B4895cd024c1625E146684940A849ED9"   # UBI Engine's public key, CP only accept the task from this UBI engine
UbiUrl ="https://ubi-task.swanchain.io/v1"                   # UBI Engine's API address

[LOG]
CrtFile = "/YOUR_DOMAIN_NAME_CRT_PATH/server.crt"            # Your domain name SSL .crt file path
KeyFile = "/YOUR_DOMAIN_NAME_KEY_PATH/server.key"            # Your domain name SSL .key file path

[HUB]
ServerUrl = "https://orchestrator-api.swanchain.io"           # The Orchestrator's API address
AccessToken = "<YOUR_Access_Token>"                            # The Orchestrator's access token, Acquired from "https://orchestrator.swanchain.io"
WalletAddress = "<YOUR_Wallet_Address>"                        # The cp‘s wallet address
BalanceThreshold= 1                                           # The cp’s collateral balance threshold
OrchestratorPk = "0x29eD49c8E973696D07E7927f748F6E5Eacd5516D" # Orchestrator's public key, CP only accept the task from this Orchestrator
VerifySign = true                                             # Verify that the task signature is from Orchestrator

[MCS]
ApiKey = "<YOUR_Api_Key>"                                   # Acquired from "https://www.multichain.storage" -> setting -> Create API Key
BucketName = "<YOUR_Bucket_Name>"                               # Acquired from "https://www.multichain.storage" -> bucket -> Add Bucket
Network = "polygon.mainnet"                   # polygon.mainnet for mainnet, polygon.mumbai for testnet
FileCachePath = "/tmp"                        # Cache directory of job data

[Registry]
ServerAddress = ""                            # The docker container image registry address, if only a single node, you can ignore
UserName = ""                                 # The login username, if only a single node, you can ignore
Password = ""                                 # The login password, if only a single node, you can ignore

[RPC]
SWAN_TESTNET ="https://rpc-proxima.swanchain.io"  # Swan testnet RPC
SWAN_MAINNET= ""                                  # Swan mainnet RPC

[CONTRACT]
SWAN_CONTRACT="0x91B25A65b295F0405552A4bbB77879ab5e38166c"              # Swan token's contract address
SWAN_COLLATERAL_CONTRACT="0xfD9190027cd42Fc4f653Dfd9c4c45aeBAf0ae063"   # Swan's collateral address
REGISTER_CP_CONTRACT = "0x38c8686347903a80160cb6cd34c63787e0ea102a"     # The CP registration contract
ZK_COLLATERAL_CONTRACT = "0x2d3758c8bd86A0C8A5F0680127847257bE4fd4f5"   # The ZK task's collateral contract address